### ISSUE TITLE
Adding E-commerce interface to the website.

### ISSUE THREAD

**Issue by ShubhangiXD** [daabChingrii/HFTNeoVogue#2]
NeoVogue is an E-commerce platform after all, while at its heart exists a gallery of talented designers, we are here to promote those ideas into marketable content.

Create an interface that includes placeholder texts and pictures and just add the front-page (on-click events that show the product description is not required in this issue).

**Comment by mainak0907** [comment]
I am interested in doing this, can I get it assigned?

**Comment by ShubhangiXD** [comment]
Hi, it's assigned to you!

**Comment by mainak0907** [comment]
Just to be clear with the requirement, the issue demands a grid displaying all the designers with a short description about 
them.

Note - I have provided a snap from a website that I have built before, only for concept reference purposes.

Let me know if the issue demands the same, please provide a clarification.

<img width="788" alt="image" src="https://github.com/daabChingrii/HFTNeoVogue/assets/88925745/cef13e75-05a5-44fb-b3d6-5cb0261abc85">
