### ISSUE TITLE
Creating an Auth Modal for the website

### ISSUE THREAD

**Issue by ShubhangiXD** [daabChingrii/HFTNeoVogue#3]
Create a database (preferably MongoDB) and make a working prototype of an authentication system for the site. Design is not your goal in this particular issue :)
The auth modal takes a username and a password to authenticate users.

**Comment by ShubhangiXD** [comment]
> do you want a express js backend code for login and signup?

Yes, the stack uses MERN so Express js is preferred!

**Comment by Ryrahul** [comment]
So I can do it by making a separate backend folder on the repo. If you are fine with it you can assign it to me

**Comment by ShubhangiXD** [comment]
Reviewing the PR by tonight, looks good though!!

**Comment by Ryrahul** [comment]
ok
